name: Block-Level-Tests

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  Block-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: 'pip'
      
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
    
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y iverilog gtkwave

      - name: Run Decoder tests
        run: |
          cd test/decoder && WAVES=0 pytest test_runner_decoder.py

      - name: Run Reg-file tests
        run: |
          cd test/reg_file && WAVES=0 pytest tests_reg_file.py

      - name: Run Program-counter tests
        run: |
          cd test/program_counter && WAVES=0 pytest tests_program_counter.py

      - name: Run CSR tests
        run: |
          cd test/csr && WAVES=0 pytest tests_csr.py